### ISSUE TITLE
Having a error pls help

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedSpawners#306] opened 2021-10-19 09:46 UTC
having an error spamming console
[latest (1).log](https://github.com/GC-spigot/AdvancedSpawners/files/7372099/latest.1.log)
l
[message (2).txt](https://github.com/GC-spigot/AdvancedSpawners/files/7372101/message.2.txt)

also another thing , mobs are not stacking , neither are spawners....

**Comment by GC-spigot** [comment] 2021-10-19 13:14
Where are you getting these spawners from? They are not from AdvancedSpawners

**Comment by el211** [comment] 2021-10-19 14:05
advanced spawners  are bugged ! even the holographic display never goes after breaking a spawner!
i am running a factions server, and one guy still has holograpg showing one spawne name after being broken!
and mobs are not stacking...

**Comment by el211** [comment] 2021-10-19 14:06
also discord support i rate this 0 
i feel like i wasted money on that plugin....

**Comment by el211** [comment] 2021-10-19 14:44
did u close my requeest ?

**Comment by el211** [comment] 2021-10-19 14:45
i am not even done yet

**Comment by GC-spigot** [comment] 2021-10-19 14:53
Relax. There's something extremely incompatible on your server. I cannot recreate your issues neither anyone else is having these. Let's start by telling me what server version you are using - copy paste text from `/version` command.
Also show me your plugin list.

**Comment by el211** [comment] 2021-10-19 15:00
![image](https://user-images.githubusercontent.com/86126606/137937151-3fdcc930-a490-431d-b014-3c7fc45affb5.png)
![image](https://user-images.githubusercontent.com/86126606/137937231-863acb0a-bfe7-4d4f-a059-7f9e23cf3ae9.png)

**Comment by GC-spigot** [comment] 2021-10-19 15:05
It says on plugin's page that any other stacking / spawner plugins aren't supported. Remove stacking & spawner plugins first from your server, then try. Should have been the logical first step :) Those are conflicting together.

**Comment by el211** [comment] 2021-10-19 16:47
i did but now mobs are stacking anymore

**Comment by GC-spigot** [comment] 2021-10-21 06:21
This plugin literally works perfectly on my server. What are you talking about? "mobs are stacking anymore" so mobs are stacking now?

All your issues are because of you not listening to what's told on plugin's page. I don't understand why you even posted your review, it's really unfair.

**Comment by el211** [comment] 2021-10-21 07:23
it is not unfair , i paid a premium plugins for several thing :
- Mobs stack , which they are not
- spawnwer stack which its it not
- Holographic display bugged on spawner after breaking , not fixed
- wiki missing all permission , i dont even have guide 
- staff never replied maybe 2 days later, like if i have a free plugin support 
- i wasted money on that plugin to be honnest .... was not expecting this kinf of support from that much priced plugin..
- I WILL CHANGE MY FEEDBACK , once eveyrhting is fixed

**Comment by GC-spigot** [comment] 2021-10-21 07:27
Guy, 1st, 2nd and 3rd issues are literally caused by incompatible plugins. Not my fault. Told you what to do :) It's also mentioned in plugin's page that such plugins aren't supported - should read before buying.
Permissions are listed in config.yml top of the file 

Staff never replied? You had the plugin for 2 days only, I replied 3 hours after you posted this ticket. Do you want me to reply instantly?
What is your problem with support? Where do you want staff to reply? You purchased this plugin 2 days ago, got pretty much instant reply here, What else do you want? I have no idea where do you expect us to reply - no tickets on Discord are opened by you in regards to this plugin, nothing has been posted in advanced spawners channel by you either.

**Comment by el211** [comment] 2021-10-21 07:51
nope its not caused by imcompatible plugin, cz i have REMOVED the plugin when u asked me

**Comment by el211** [comment] 2021-10-21 07:55
and staff never replies instantly , this is not premium support.... 
i am very disappointed , but i will still change my feedback once my issue is solved

**Comment by GC-spigot** [comment] 2021-10-21 08:03
Why should we reply instantly? My mom is sick, I'm taking care of her - I can't be on my computer all the time because someone feels entitled to have an instant response. Staff have school, personal lives. No premium plugins have instant responses 24/7, remember plugins are a hobby, not a job for people.

100% all of your issues are caused by incompatible plugins. I can make you a server and show that my plugin works perfectly without other plugins - so there's something still incompatible. You have many plugins, don't know them all myself, can't tell you which ones may be causing issues. Start removing plugins by a few until you don't have problems then you'll find what's causing them.

**Comment by el211** [comment] 2021-10-21 08:50
i have removed all of my spawner plugin 
i dont have any incompatible plugin anymore i removed all the plugins related to mobs 
and i still have this problem

**Comment by GC-spigot** [comment] 2021-10-21 09:03
I told you what to do - start removing all until this is fixed. There’s nothing else I can help you with - this isn’t a problem with my plugin.

**Comment by el211** [comment] 2021-10-21 09:08
you told me what to remove and I DID .

still plugin is not working

**Comment by GC-spigot** [comment] 2021-10-21 09:11
“ You have many plugins, don't know them all myself, can't tell you which ones may be causing issues. Start removing plugins by a few until you don't have problems then you'll find what's causing them.” i told you this

**Comment by el211** [comment] 2021-10-21 09:21
all the plugins are pvp plugins nothing related to mobs ,,,,,,
hi have removed all pluguns related to mobs and spawners

**Comment by el211** [comment] 2021-10-24 09:56
listen man i bought a premium plugin so hat ur staff mute me cz its been 5 days i have NO SUPPORT 
and at the end i got banned from the discord 
so i paid money lots of money on ur plugins i bought them all , i am gonna do  paypal chargeback i got screenshots of all conversations , Support sucks , firosee the admin is  "stupid" sorry for that word he taggs me all the time , if i tag him he mutes me lol then ban me xD
So i am being honnest with you i didnt get what i paid for , so thats a reason for me to open a paypal case , i gave ur  staff my word that i will wait until tuesday if nothing happens i got all screenshots of tickets even thoe i got banned i will just send it to paypal and let them know 
and i will update my feedback stating this is a SCAM

**Comment by GC-spigot** [comment] 2021-10-24 10:17
Guy, have you noticed that you have no patience and am extremely toxic? I replied hours within your report on here, gave you a suggestion- these issues, are not caused by my plugin. Something is interfering. Told you how you can find the problem. I don’t see a point in continuing this discussion if you don’t want to listen to my suggestions

**Comment by el211** [comment] 2021-10-24 11:51
Lol so i am toxic ?  I PAID TO GET UR PLUGIN IF U TREAT PEOPLE LIKE THAT THEN DONT GET UR PUGIN AS A PREMIUM ONE 
CZZ ITS NOT !
ITS FAR FORM BEOING A PREMIUM PLUGIN , ITS ACTUALLY A HUGE SCAM , PLUGIN NOT WORKING , AND ENDING UP BANNING ME Xd
I HOLD MY WORD ANY WAY ILL WAIT UNTIL TUESAY IF I AM NOT BACK ON DISCORD , AND IF I DONT GET THE SUPPORT I DESERVE I AM OPENING A CASE ON ALL PLUGINS FOR ITEM NOT MATCHING WHAT I PAID.

CZ CLEARLY I DID NOT RECEIVE WHAT I PAID FOR

**Comment by el211** [comment] 2021-10-24 11:52
I AM NOT A RANDOM GUY ON UR DISCORD CHANNEL
I AM A CUSTOMER THAT PAID UR PLUGINS

**Comment by GC-spigot** [comment] 2021-10-24 11:56
Why are you using caps? Just further proves my point. Go ahead and open a chargeback then, don’t threaten. You agreed to our terms of service - no refunds. You will lose it, so please do open one.

I literally am handicapped and can’t help you any other way. Just do what I said or chargeback, not replying anymore until there is progress.

**Comment by el211** [comment] 2021-10-24 12:25
U Kidding me ? for the 10000th time i am telling u i DID WHAT U SAID 
and did not work 

anyway i hols my word , if u think i will losse chargeback u r wrong , that is not the first time i am charging back item not as described and a scam cz u kicked me form discord with no support

But i am a men of my word i will wait until tuesday 
if nothing then i will chargeback , cz i want paypal support to see i have been giving u time do do things right

**Comment by GC-spigot** [comment] 2021-10-24 12:43
I did not kick you from the discord, staff did. They wouldn’t unless it’s valid.

You did not follow my steps. Told you to remove all plugins by a couple at a time, until issues are resolved. My product works as described, I can prove it. Can you prove you listened to my steps? 

You don’t want my help, otherwise you’d follow instructions I gave. You are not going to win this chargeback, just showing how you are communicating is enough.

 If your next reply is about the same thing again, with no progress being done on actual ticket and just telling that I’m not helping when I’m replying constantly, just gonna close this ticket.

**Comment by el211** [comment] 2021-10-24 12:59
I DID WHAT U SAID !

want a video prooff ?

**Comment by el211** [comment] 2021-10-24 12:59
AND EVEN THOE IF THE STAFF KICKED ME THEN REVIEW UR STAFF

**Comment by el211** [comment] 2021-10-24 13:00
cz i was okay to be patient and wait but ur staff made me 100times more angry , u are getting that fedback mostly because of ur staff specially that junk admin Firosee

**Comment by D4rkBytePT** [comment] 2021-10-24 21:12
el211 please be patient and do it step by step, remove all plugins, and put only AdvancedSpawners, try it to see if the case is still the same, in case it is not, put plugin by plugin and test until you find out which plugin is giving conflict and please do not blame the GC for bad support as he is doing his best to help everyone that needs support, after all, you are not the only one who is here for support and for some problem that the plugin may have that has not been fixed yet or has not told a way to fix it, being that the GC has already said that he has to take care of his mother who has cancer.

Thanks for your understanding

**Comment by el211** [comment] 2021-10-25 08:24
u think i havent done that already ? why do u think i am that angry.... 
cz i have done that multiple time .... i run a big server i was expecting a premium plugin with premium support not a plugin that support member bans customer from discord 
and no help for days ,......

**Comment by el211** [comment] 2021-10-25 14:00
at gcspawners.ShopInventoryClick.onClick(ShopInventoryClick.java:41) ~[AdvancedSpawners-3.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2802) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1528) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:55:40 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v3.4.6
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at gcspawners.ShopInventoryClick.onClick(ShopInventoryClick.java:41) ~[AdvancedSpawners-3.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2802) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:55:40 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v3.4.6
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at gcspawners.ShopInventoryClick.onClick(ShopInventoryClick.java:41) ~[AdvancedSpawners-3.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2802) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:55:41 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v3.4.6
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at gcspawners.ShopInventoryClick.onClick(ShopInventoryClick.java:41) ~[AdvancedSpawners-3.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2802) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:55:41 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v3.4.6
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at gcspawners.ShopInventoryClick.onClick(ShopInventoryClick.java:41) ~[AdvancedSpawners-3.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2802) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:55:41 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v3.4.6
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at gcspawners.ShopInventoryClick.onClick(ShopInventoryClick.java:41) ~[AdvancedSpawners-3.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-311]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2802) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by el211** [comment] 2021-10-25 14:00
HERE 
all this in a empty server
no plugins

**Comment by el211** [comment] 2021-10-25 14:02
https://user-images.githubusercontent.com/86126606/138709866-b47e721c-ff3b-47bf-a25a-69aa1562a0f9.mp4

here is a video recording in case u dont believe me

**Comment by GC-spigot** [comment] 2021-10-25 14:20
Add Vault plugin to your server. What about your other issues with spawning - are they now fixed?

**Comment by el211** [comment] 2021-10-25 14:33
nope not fixed same thing , even get worse 
now when i do /spawnershop i try to buy a spawner i cant even buy it anymore

**Comment by GC-spigot** [comment] 2021-10-25 14:39
That's not worse, I told you what to do - add Vault to your server :)

**Comment by el211** [comment] 2021-10-25 15:05
okay it worked ...
but i had to remove all of my plugins :/

**Comment by GC-spigot** [comment] 2021-10-25 15:13
Told you it's gonna work :) 

Now, what you can do is start adding back plugins by like 2-3 at a time. Add them, then restart and see if issues start happening. If issues are happening again, one of those plugins will be at fault. Once you find those plugins, let me know and I'll help you out!

**Comment by el211** [comment] 2021-10-27 08:04
idk what is the issue but the only thing is the holographic display that stays bugged when we break a spawner but for some reason on my second server ther is no holographic display at all ...
anyway i will change my feedback ...
can i be reinvited to the discord?

**Comment by GC-spigot** [comment] 2021-10-28 07:38
Sure, what's your discord username?

Will wait for your feedback to change - told you that just try removing plugins until you find the issue.
What holograms plugin are you using - usually holograms stay if some other plugin interferes with spawner breaking and doesn't let AdvancedSpawners know that spawner was broken - that's why I believed there were issues.

make sure you have HolographicDisplays installed on your second server - it's required

**Comment by el211** [comment] 2021-10-28 11:41
i have removed my bad  feedback..... 
i will add a different one once i am back on discord 
i dont have holographic display installed otherwise it will lag like it was doing before

**Comment by GC-spigot** [comment] 2021-10-28 12:12
Sure, what's your discord username?

**Comment by el211** [comment] 2021-10-28 13:20
Blueee#0001

**Comment by el211** [comment] 2021-10-28 13:20
Blueee#0001

**Comment by el211** [comment] 2021-10-28 13:20
its # 001

**Closed as completed** 2021-11-01 12:31 UTC
Labels: issue
